export declare const regular: () => JSX.Element;
export declare const small: () => JSX.Element;
export declare const large: () => JSX.Element;
export declare const withAvatarUrl: () => JSX.Element;
export declare const withUrlFallbackToInitials: () => JSX.Element;
export declare const markedAsExternal: () => JSX.Element;
export declare const withBadges: () => JSX.Element;
export declare const withMultipleAvatars: () => JSX.Element;
export declare const withoutNameOrInitials: () => JSX.Element;
declare const _default;
export default _default;
